### ISSUE TITLE
ImportError as of black v22.8.0

### ISSUE THREAD

**Issue by tpansino** [LilSpazJoekp/docstrfmt#47]
Running this tool as a pre-commit hook, I'm currently getting:

```
docstrfmt................................................................Failed
- hook id: docstrfmt
- exit code: 1

Traceback (most recent call last):
  File "/home/dev/.cache/pre-commit/repo7rlkfiuk/py_env-python3/bin/docstrfmt", line 5, in <module>
    from docstrfmt.main import main
  File "/home/dev/.cache/pre-commit/repo7rlkfiuk/py_env-python3/lib/python3.10/site-packages/docstrfmt/main.py", line 20, in <module>
    from black import (
ImportError: cannot import name 'cancel' from 'black' (/home/dev/.cache/pre-commit/repo7rlkfiuk/py_env-python3/lib/python3.10/site-packages/black/__init__.cpython-310-x86_64-linux-gnu.so)
```

Pinning black to v22.6.0 (via pre-commit `additional_dependencies` arg) fixes the issue, so I assume it's related in some way.

**Comment by LilSpazJoekp** [comment]
This should be fixed. Would you mind testing and confirming for me?

**Comment by tpansino** [comment]
Yes, I can confirm it's working now.

Thanks so much for your quick response!

**Comment by LilSpazJoekp** [comment]
No problem! Thanks for reporting
